name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]


    steps:
    - uses: actions/checkout@v2
      with:
        # Need to download submodules to have access to test cases for CI
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@dicekeys'
    - name: Install dependencies
      run: |
        cd common
        npm ci
        cd ../web
        npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
        cd common
        npm run build
        cd ../web
        npm run build --if-present
    - name: Run tests
      run: |
        cd web
        npm test
      env:
        CI: true
